apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - pvc.yaml
  - statefulset.yaml
  - init-databases-configmap.yaml
  - ensure-integrations-database-job.yaml
  - migrate-boutique-platform-types-job.yaml
