apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: discovery-server
  ports:
    - name: http
      port: 8761
      targetPort: http
