apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  labels:
    app.kubernetes.io/name: stock-service
    app.kubernetes.io/part-of: intelliops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stock-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stock-service
        app.kubernetes.io/part-of: intelliops
    spec:
      containers:
        - name: stock-service
          image: docker.io/abdellatifbiti03/erp-stock-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://erp-db:5432/erp_stocks
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: erp-kafka:29092
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            failureThreshold: 48
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
