apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: stock-service
  ports:
    - name: http
      port: 8084
      targetPort: http
