apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discovery-server
  - config-server
  - user-service
  - lead-service
  - abonnement-service
  - stock-service
  - paiement-service
  - delivery-service
  - notification-service
  - gateway-service
  - mcp-server
  - frontend
