apiVersion: v1
kind: Service
metadata:
  name: store-integration-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: store-integration-service
  ports:
    - name: http
      port: 8090
      targetPort: http
