apiVersion: v1
kind: Service
metadata:
  name: erp-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: erp-kafka
  ports:
    - name: broker
      port: 29092
      targetPort: broker
    - name: controller
      port: 29093
      targetPort: controller