apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intelliops-dev

resources:
  - ../../base
  - ../../../../platform/postgres/base
  - ../../../../platform/kafka/base
  - ../../../../platform/minio/base
  - ingress.yaml
images:
  - name: docker.io/abdellatifbiti03/erp-discovery-server
    newTag: 0d7e869f43504adf3c48165e25d94448e3d8b70d
  - name: docker.io/abdellatifbiti03/erp-config-server
    newTag: 0d7e869f43504adf3c48165e25d94448e3d8b70d
  - name: docker.io/abdellatifbiti03/erp-user-service
    newTag: d15a8812ba1e24ba3b780b0d6c4357ccfff3e1db
  - name: docker.io/abdellatifbiti03/erp-lead-service
    newTag: d15a8812ba1e24ba3b780b0d6c4357ccfff3e1db
  - name: docker.io/abdellatifbiti03/erp-abonnement-service
    newTag: e83c9eb95bb4892771fdd0f68013e31f907bb4a2
  - name: docker.io/abdellatifbiti03/erp-stock-service
    newTag: e83c9eb95bb4892771fdd0f68013e31f907bb4a2
  - name: docker.io/abdellatifbiti03/erp-paiement-service
    newTag: e83c9eb95bb4892771fdd0f68013e31f907bb4a2
  - name: docker.io/abdellatifbiti03/erp-delivery-service
    newTag: d15a8812ba1e24ba3b780b0d6c4357ccfff3e1db
  - name: docker.io/abdellatifbiti03/erp-notification-service
    newTag: e83c9eb95bb4892771fdd0f68013e31f907bb4a2
  - name: docker.io/abdellatifbiti03/erp-store-integration-service
    newTag: d15a8812ba1e24ba3b780b0d6c4357ccfff3e1db
  - name: docker.io/abdellatifbiti03/erp-gateway-service
    newTag: e83c9eb95bb4892771fdd0f68013e31f907bb4a2
  - name: docker.io/abdellatifbiti03/erp-mcp-server
    newTag: e83c9eb95bb4892771fdd0f68013e31f907bb4a2
  - name: docker.io/abdellatifbiti03/erp-frontend-service
    newTag: e83c9eb95bb4892771fdd0f68013e31f907bb4a2
